In [4]:
import pandas as pd

In [5]:
produtos = pd.read_csv(r'../../data/Produto.csv', encoding='ISO-8859-1')

soja = produtos[produtos['DESCRICAO'] == 'SOJA']
soja

     #CODIGO DESCRICAO DATA_INICIO DATA_FIM
373     6720      SOJA  14/05/2012      NaN

In [6]:
empreendimento = pd.read_csv(r'../../data/Empreendimento.csv', sep=';', encoding='ISO-8859-1')
cod_empreendimento =  empreendimento[empreendimento['PRODUTO'] == 'SOJA']
cod_empreendimento

,CODIGO,DATA_INICIO,DATA_FIM,FINALIDADE,ATIVIDADE,MODALIDADE,PRODUTO,VARIEDADE,CESTA,ZONEAMENTO,UNIDADE_MEDIDA,UNIDADE_MEDIDA_PREVISAO,CONSORCIO,CEDULA_MAE,CD_TIPO_CULTURA
57,"1,20E+13",23/02/2017,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
58,"1,20E+13",23/02/2017,25/06/2020,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safrinha (2ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
59,"1,20E+13",01/01/1984,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Consorciado,0.0,3.0
60,"1,20E+13",24/08/2005,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Irrigadas,Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
61,"1,20E+13",01/01/1984,25/06/2020,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safrinha (2ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
62,"1,20E+13",01/01/1984,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
63,"1,20E+13",01/07/2006,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
64,"1,20E+13",14/03/2017,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Irrigadas,NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
914,"1,20E+13",01/01/2013,30/06/2015,Custeio,Agrícola,LAVOURA,SOJA,CULTIVO EM SISTEMAS INTEGRADOS,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
1127,"1,40E+13",01/07/2016,NaN,NaN,Agrícola,BENEFICIAMENTO OU INDUSTRIALIZAÇÃO,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Unidade,Valor inválido,0.0,NaN
1207,"1,20E+13",01/01/1984,30/06/2016,Custeio,Agrícola,BENEFICIAMENTO OU INDUSTRIALIZAÇÃO,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1619,"1,12E+13",01/04/2012,30/08/2018,Comercialização,Agrícola,FEPM (EX-EGF) - encerrado,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
1658,"1,12E+13",01/01/2014,30/06/2018,Comercialização,Agrícola,FEPM (EX-EGF) - encerrado,SOJA,VARIEDADE,Safrinha (2ª Safra),Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,3.0
1678,"1,12E+13",19/07/2018,NaN,Comercialização,Agrícola,FEE (EX-LEC),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Quilograma,Unidade,Valor inválido,0.0,3.0
1722,"1,12E+13",21/08/2020,NaN,Comercialização,Agrícola,FEE (EX-LEC),SOJA,SEMENTE,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
1756,"1,12E+13",01/01/1984,30/06/2022,Comercialização,Agrícola,PRÉ-COMERCIALIZAÇÃO - encerrado,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
1875,"1,12E+13",01/01/1984,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1972,"1,12E+13",19/06/2005,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,FARELO,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1979,"1,12E+13",01/01/2007,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,ÓLEO BRUTO DEGOMADO,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1990,"1,12E+13",01/01/2013,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,VARIEDADE,Safra de Verão (1ª Safra),Zoneado,Saca de 60 Quilos,Tonelada,Não consorciado,0.0,3.0
2003,"1,12E+13",01/01/2015,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,SEMENTE,Safra de Verão (1ª Safra),Zoneado,Saca de 60 Quilos,Tonelada,Não consorciado,0.0,NaN
2050,"1,12E+13",01/01/2002,NaN,Comercialização,Agrícola,CPR (CÉDULA DE PRODUTO RURAL),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
2152,"1,13E+13",01/01/1984,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
2207,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,FARELO,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2229,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,SEMENTE,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2247,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,EM GRÃOS,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2377,"1,44E+13",01/07/2016,11/10/2016,NaN,Agrícola,ATENDIMENTO A COOPERADOS (MCR 5-2),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2438,"1,12E+13",01/01/2015,05/07/2021,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2477,"1,12E+13",01/07/2015,27/09/2018,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,FARELO,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2497,"1,12E+13",20/07/2017,27/09/2018,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,ÓLEO,Ano Civil / Ano de Exploração,NaN,Litro,Litro,Valor inválido,0.0,NaN
2529,"1,13E+13",01/07/2013,NaN,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
2530,"1,13E+13",01/07/2013,22/11/2018,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
2531,"1,13E+13",21/06/2022,30/06/2022,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Tonelada,Tonelada,Não consorciado,0.0,3.0
2614,"1,13E+13",01/01/2014,30/06/2017,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,VARIEDADE,Safrinha (2ª Safra),Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,3.0
2829,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2830,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2831,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Irrigadas,Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2832,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Irrigadas,Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2923,"1,30E+13",14/04/2020,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2924,"1,30E+13",09/02/2021,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
2925,"1,30E+13",09/02/2021,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2965,"1,13E+13",17/08/2017,13/09/2017,Comercialização,Agrícola,Financiamento para Aquisição da Produção/Mater...,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,3.0

In [7]:
operacao_credito_estadual = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_OPERACAO_BASICA_ESTADO_2018_ATUAL.csv', sep=';', encoding='ISO-8859-1')
operacao_credito_estadual_antes = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_OPERACAO_BASICA_ESTADO_2013_2017.csv', sep=';', encoding='ISO-8859-1')

In [8]:
operacao_credito_estadual_total =pd.concat([operacao_credito_estadual,operacao_credito_estadual_antes], axis=0)

In [9]:
ref_bacen = operacao_credito_estadual_total[operacao_credito_estadual_total['CD_EMPREENDIMENTO'].isin(set(cod_empreendimento['CODIGO']))]
ref_bacen

,REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,...,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN
4,510409466,1,79342069,07/17/2020 00:00:00,04/15/2021 00:00:00,5,3333,300,NaN,PR,...,78.70,NaN,NaN,02/15/2021 00:00:00,10/13/2020 00:00:00,02/12/2021 00:00,10/10/2020 00:00,NaN,NaN,NaN
5,512711289,1,89990501,09/09/2021 00:00,07/20/2022 00:00:00,5,2222,201,1181521.0,RS,...,13.56,1.0,NaN,04/25/2022 00:00:00,11/01/2021 00:00,02/25/2022 00:00:00,09/10/2021 00:00,NaN,NaN,"2,02E+12"
8,513444051,1,79342069,02/02/2022 00:00,11/11/2022 00:00,5,3333,300,NaN,PR,...,64.22,NaN,NaN,08/20/2022 00:00:00,03/10/2022 00:00,08/10/2022 00:00,03/08/2022 00:00,NaN,NaN,"2,02E+12"
21,511110828,1,0,10/30/2020 00:00:00,11/29/2021 00:00:00,3,4444,430,NaN,MT,...,670.00,NaN,NaN,06/30/2021 00:00:00,02/15/2021 00:00:00,06/01/2021 00:00,02/01/2021 00:00,NaN,10.75,NaN
26,512498723,1,92702067,08/10/2021 00:00,05/20/2022 00:00:00,1,2222,201,NaN,RS,...,2.33,1.0,NaN,02/15/2022 00:00:00,09/15/2021 00:00:00,01/15/2022 00:00:00,08/15/2021 00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048561,7867054,1,81011686,05/12/2016 00:00,05/30/2017 00:00:00,4,2222,403,NaN,SC,...,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048565,8564740,1,2446089,08/19/2016 00:00:00,08/15/2017 00:00:00,5,2222,505,NaN,PR,...,1.21,1.0,11.49,03/31/2017 00:00:00,10/31/2016 00:00:00,03/01/2017 00:00,10/01/2016 00:00,NaN,NaN,NaN
1048568,5663687,1,2663426,05/06/2015 00:00,02/15/2016 00:00:00,5,2222,201,NaN,RS,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,5240839,1,0,01/29/2015 00:00:00,01/28/2016 00:00:00,10,2222,300,NaN,MG,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,505468859,1,0,09/12/2017 00:00,08/15/2018 00:00:00,4,3333,201,NaN,SC,...,0.85,NaN,NaN,06/16/2018 00:00:00,12/12/2017 00:00,01/15/2018 00:00:00,10/13/2017 00:00:00,NaN,NaN,NaN

In [69]:
sicor_cop_basico = pd.read_csv("C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_COP_BASICO.csv", sep=';', encoding='ISO-8859-1')
sicor_cop_basico = sicor_cop_basico.drop(columns=['DT_FIM_COLHEITA', 'DT_FIM_PLANTIO', 'DT_INICIO_PLANTIO', 'DT_INICIO_COLHEITA'])
sicor_cop_basico

,REF_BACEN,NU_ORDEM,DT_COMUNICACAO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,508778190,1,03/12/2020 00:00,2,3,3,48
1,508651375,1,03/13/2020 00:00:00,2,1,3,48
2,3320273,1,08/26/2014 00:00:00,2,1,3,48
3,512735896,1,04/29/2022 00:00:00,2,3,3,48
4,6590243,1,03/17/2016 00:00:00,2,3,3,48
...,...,...,...,...,...,...,...
581000,9717627,1,09/27/2017 00:00:00,2,1,2,48
581001,509346910,1,01/24/2020 00:00:00,2,3,2,48
581002,6170376,1,09/18/2015 00:00:00,2,3,2,24
581003,9449462,1,07/21/2017 00:00:00,2,1,3,17
581004,508608147,1,10/22/2019 00:00:00,2,99,9,31

In [73]:
merged = ref_bacen.merge(sicor_cop_basico, on=['REF_BACEN', 'NU_ORDEM'], how='inner')
merged.to_csv("xove.csv")

In [61]:
glebas = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/03_TABS_COMP_BASICAS_OPERACOES_CREDITO_RURAL_PROAGRO_RECURSOS_PUB/Glebas.csv', sep=';', encoding='ISO-8859-1')
glebas_soja = glebas[(glebas['REF_BACEN'].isin(set(merged['REF_BACEN']))) & (glebas['NU_ORDEM'].isin(set(merged['NU_ORDEM'])))]
glebas_soja

,REF_BACEN,NU_ORDEM,NU_IDENTIFICADOR,NU_INDICE_GLEBA,NU_INDICE_PONTO,VL_LATITUDE,VL_LONGITUDE,CGL_VL_ALTITUDE
0,514166720,1,1,0,17,"-28,105725","-52,845429","533,61"
2,505279469,1,1,0,16,"-27,509908","-52,822073","564,66"
4,510160257,1,5,4,23,"-28,585877","-52,120624","678,4"
5,513678782,1,1,2,29,"-27,581412","-52,909909","494,58"
10,509573108,1,2844600,0,1,"-21,95682","-54,977416",0
...,...,...,...,...,...,...,...,...
1048560,512967973,1,6,5,52,"-23,193704","-50,500879","472,34"
1048561,514319387,1,3472067,0,28,"-31,584751","-53,41307",0
1048565,512312032,1,3,2,28,"-27,937906","-53,11623","394,27"
1048567,508303470,1,1,0,5,"-27,401514","-53,971427",0
1048572,504865528,1,258685,5,38,"-15,814091","-47,542896",0

In [62]:
count_registers = glebas_soja['REF_BACEN'].value_counts()

codigos_a_remover = count_registers[count_registers <= 3].index.tolist()

final = glebas_soja[~glebas_soja['REF_BACEN'].isin(codigos_a_remover)]

In [74]:
sicor_op_glebas = pd.merge(final, merged, on=['REF_BACEN', 'NU_ORDEM'], how='left')
sicor_op_glebas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266033 entries, 0 to 266032
Data columns (total 53 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   REF_BACEN                  266033 non-null  int64
 1   NU_ORDEM                   266033 non-null  int64
 2   NU_IDENTIFICADOR           266033 non-null  int64
 3   NU_INDICE_GLEBA            266033 non-null  int64
 4   NU_INDICE_PONTO            266033 non-null  int64
 5   VL_LATITUDE                266033 non-null  object
 6   VL_LONGITUDE               266033 non-null  object
 7   CGL_VL_ALTITUDE            266033 non-null  object
 8   CNPJ_IF                    60159 non-null   float64
 9   DT_EMISSAO                 60159 non-null   object
 10  DT_VENCIMENTO              60159 non-null   object
 11  CD_INST_CREDITO            60159 non-null   float64
 12  CD_CATEG_EMITENTE          60159 non-null   float64
 13  CD_FONTE_RECURSO           60159 non-null   float64
 14  CNPJ_AGENTE_INVEST         12487 non-null   float64
 15  CD_ESTADO                  60159 non-null   object
 16  CD_REF_BACEN_INVESTIMENTO  12487 non-null   float64
 17  CD_TIPO_SEGURO             60159 non-null   float64
 18  CD_EMPREENDIMENTO          60159 non-null   object
 19  CD_PROGRAMA                60159 non-null   float64
 20  CD_TIPO_ENCARG_FINANC      41462 non-null   float64
 21  CD_TIPO_IRRIGACAO          60159 non-null   float64
 22  CD_TIPO_AGRICULTURA        60159 non-null   float64
 23  CD_FASE_CICLO_PRODUCAO     60159 non-null   float64
 24  CD_TIPO_CULTIVO            60159 non-null   float64
 25  CD_TIPO_INTGR_CONSOR       60159 non-null   float64
 26  CD_TIPO_GRAO_SEMENTE       60159 non-null   float64
 27  VL_ALIQ_PROAGRO            60159 non-null   float64
 28  VL_JUROS                   60159 non-null   float64
 29  VL_PRESTACAO_INVESTIMENTO  12487 non-null   float64
 30  VL_PREV_PROD               60154 non-null   float64
 31  VL_QUANTIDADE              467 non-null     float64
 32  VL_RECEITA_BRUTA_ESPERADA  60159 non-null   float64
 33  VL_PARC_CREDITO            60159 non-null   float64
 34  VL_REC_PROPRIO             31267 non-null   float64
 35  VL_PERC_RISCO_STN          18501 non-null   float64
 36  VL_PERC_RISCO_FUNDO_CONST  18547 non-null   float64
 37  VL_REC_PROPRIO_SRV         46639 non-null   float64
 38  VL_AREA_FINANC             60159 non-null   float64
 39  CD_SUBPROGRAMA             48078 non-null   float64
 40  VL_PRODUTIV_OBTIDA         10462 non-null   float64
 41  DT_FIM_COLHEITA            59562 non-null   object
 42  DT_FIM_PLANTIO             58683 non-null   object
 43  DT_INIC_COLHEITA           59562 non-null   object
 44  DT_INIC_PLANTIO            58683 non-null   object
 45  VL_JUROS_ENC_FINAN_POSFIX  0 non-null       float64
 46  VL_PERC_CUSTO_EFET_TOTAL   21538 non-null   float64
 47  CD_CONTRATO_STN            13786 non-null   object
 48  DT_COMUNICACAO             60159 non-null   object
 49  CD_STATUS                  60159 non-null   float64
 50  CD_CICLO_CULTIVAR          60159 non-null   float64
 51  CD_TIPO_SOLO               60159 non-null   float64
 52  CD_EVENTO                  60159 non-null   float64
dtypes: float64(35), int64(5), object(13)
memory usage: 107.6+ MB

In [75]:
relatorio_glebas = sicor_op_glebas[['REF_BACEN',	'NU_ORDEM',	'DT_EMISSAO',	'DT_VENCIMENTO',	'CD_ESTADO',	'CD_EMPREENDIMENTO',	'CD_PROGRAMA'	,'CD_TIPO_IRRIGACAO'	,'CD_TIPO_AGRICULTURA',	'CD_FASE_CICLO_PRODUCAO',	'CD_TIPO_CULTIVO',	'CD_TIPO_GRAO_SEMENTE',	'DT_FIM_COLHEITA',	'DT_FIM_PLANTIO','DT_INIC_COLHEITA','DT_INIC_PLANTIO','DT_COMUNICACAO','CD_CICLO_CULTIVAR','CD_TIPO_SOLO',	'CD_EVENTO']]
relatorio_glebas

,REF_BACEN,NU_ORDEM,DT_EMISSAO,DT_VENCIMENTO,CD_ESTADO,CD_EMPREENDIMENTO,CD_PROGRAMA,CD_TIPO_IRRIGACAO,CD_TIPO_AGRICULTURA,CD_FASE_CICLO_PRODUCAO,CD_TIPO_CULTIVO,CD_TIPO_GRAO_SEMENTE,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,DT_COMUNICACAO,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,514166720,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,505279469,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,510160257,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,513678782,1,04/06/2022 00:00,02/15/2023 00:00:00,RS,"1,20E+13",1.0,1.0,3.0,22.0,0.0,8.0,11/17/2022 00:00:00,06/30/2022 00:00:00,10/19/2022 00:00:00,06/01/2022 00:00,11/01/2022 00:00,2.0,3.0,17.0
4,509573108,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266028,512967973,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266029,514319387,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266030,512312032,1,07/16/2021 00:00:00,05/30/2022 00:00:00,RS,"1,20E+13",1.0,1.0,5.0,22.0,0.0,8.0,02/28/2022 00:00:00,09/06/2021 00:00,02/28/2022 00:00:00,09/05/2021 00:00,12/06/2021 00:00,2.0,3.0,48.0
266031,508303470,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266032,504865528,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN