In [7]:
import pandas as pd

In [8]:
produtos = pd.read_csv(r'../../data/Produto.csv', encoding='ISO-8859-1')

soja = produtos[produtos['DESCRICAO'] == 'SOJA']
soja

     #CODIGO DESCRICAO DATA_INICIO DATA_FIM
373     6720      SOJA  14/05/2012      NaN

In [9]:
sicor_basico = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_OPERACAO_BASICA_ESTADO_2018_ATUAL.csv', sep=';', encoding='ISO-8859-1')
sicor_basico

,REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,...,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN
0,510719466,1,7237373,08/26/2020 00:00:00,08/26/2022 00:00:00,5,2222,502,NaN,BA,...,0.00,56.0,NaN,NaN,NaN,NaN,NaN,NaN,0.50,NaN
1,511579352,1,91884981,02/18/2021 00:00:00,05/15/2027 00:00:00,5,4444,505,NaN,GO,...,0.00,30.0,NaN,NaN,NaN,NaN,NaN,7.5,7.50,NaN
2,508433795,1,0,05/28/2019 00:00:00,05/27/2020 00:00:00,10,2222,304,NaN,PR,...,4.37,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,511618281,1,0,02/24/2021 00:00:00,02/15/2027 00:00:00,1,3333,303,NaN,MG,...,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.14,NaN
4,510409466,1,79342069,07/17/2020 00:00:00,04/15/2021 00:00:00,5,3333,300,NaN,PR,...,78.70,NaN,NaN,02/15/2021 00:00:00,10/13/2020 00:00:00,02/12/2021 00:00,10/10/2020 00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,510529873,2,7237373,07/31/2020 00:00:00,07/31/2030 00:00:00,5,2222,502,NaN,PE,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN
1048570,512929780,1,7237373,10/14/2021 00:00:00,10/14/2023 00:00:00,5,2222,502,NaN,PE,...,0.00,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,506396652,1,0,03/23/2018 00:00:00,03/05/2028 00:00,1,2222,300,NaN,RS,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,515263617,1,804046,12/29/2022 00:00:00,10/17/2023 00:00:00,4,2222,201,NaN,MG,...,5.48,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5.50,NaN
1048573,506196425,1,1181521,01/31/2018 00:00:00,01/15/2028 00:00:00,4,2222,505,NaN,RS,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
empreendimento = pd.read_csv(r'../../data/Empreendimento.csv', sep=';', encoding='ISO-8859-1')
cod_empreendimento =  empreendimento[empreendimento['PRODUTO'] == 'SOJA']
cod_empreendimento

,CODIGO,DATA_INICIO,DATA_FIM,FINALIDADE,ATIVIDADE,MODALIDADE,PRODUTO,VARIEDADE,CESTA,ZONEAMENTO,UNIDADE_MEDIDA,UNIDADE_MEDIDA_PREVISAO,CONSORCIO,CEDULA_MAE,CD_TIPO_CULTURA
57,"1,20E+13",23/02/2017,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
58,"1,20E+13",23/02/2017,25/06/2020,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safrinha (2ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
59,"1,20E+13",01/01/1984,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Consorciado,0.0,3.0
60,"1,20E+13",24/08/2005,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Irrigadas,Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
61,"1,20E+13",01/01/1984,25/06/2020,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safrinha (2ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
62,"1,20E+13",01/01/1984,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
63,"1,20E+13",01/07/2006,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
64,"1,20E+13",14/03/2017,NaN,Custeio,Agrícola,LAVOURA,SOJA,NÃO SE APLICA,Irrigadas,NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
914,"1,20E+13",01/01/2013,30/06/2015,Custeio,Agrícola,LAVOURA,SOJA,CULTIVO EM SISTEMAS INTEGRADOS,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
1127,"1,40E+13",01/07/2016,NaN,NaN,Agrícola,BENEFICIAMENTO OU INDUSTRIALIZAÇÃO,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Unidade,Valor inválido,0.0,NaN
1207,"1,20E+13",01/01/1984,30/06/2016,Custeio,Agrícola,BENEFICIAMENTO OU INDUSTRIALIZAÇÃO,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1619,"1,12E+13",01/04/2012,30/08/2018,Comercialização,Agrícola,FEPM (EX-EGF) - encerrado,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
1658,"1,12E+13",01/01/2014,30/06/2018,Comercialização,Agrícola,FEPM (EX-EGF) - encerrado,SOJA,VARIEDADE,Safrinha (2ª Safra),Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,3.0
1678,"1,12E+13",19/07/2018,NaN,Comercialização,Agrícola,FEE (EX-LEC),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Quilograma,Unidade,Valor inválido,0.0,3.0
1722,"1,12E+13",21/08/2020,NaN,Comercialização,Agrícola,FEE (EX-LEC),SOJA,SEMENTE,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
1756,"1,12E+13",01/01/1984,30/06/2022,Comercialização,Agrícola,PRÉ-COMERCIALIZAÇÃO - encerrado,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
1875,"1,12E+13",01/01/1984,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1972,"1,12E+13",19/06/2005,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,FARELO,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1979,"1,12E+13",01/01/2007,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,ÓLEO BRUTO DEGOMADO,Ano Civil / Ano de Exploração,Não zoneado,Tonelada,Unidade,Não consorciado,0.0,3.0
1990,"1,12E+13",01/01/2013,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,VARIEDADE,Safra de Verão (1ª Safra),Zoneado,Saca de 60 Quilos,Tonelada,Não consorciado,0.0,3.0
2003,"1,12E+13",01/01/2015,NaN,Comercialização,Agrícola,DESCONTO (NPR E DR),SOJA,SEMENTE,Safra de Verão (1ª Safra),Zoneado,Saca de 60 Quilos,Tonelada,Não consorciado,0.0,NaN
2050,"1,12E+13",01/01/2002,NaN,Comercialização,Agrícola,CPR (CÉDULA DE PRODUTO RURAL),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
2152,"1,13E+13",01/01/1984,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Unidade,Não consorciado,0.0,3.0
2207,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,FARELO,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2229,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,SEMENTE,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2247,"1,13E+13",01/01/2015,NaN,Comercialização,Agrícola,ESTOCAGEM,SOJA,EM GRÃOS,Ano Civil / Ano de Exploração,Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,NaN
2377,"1,44E+13",01/07/2016,11/10/2016,NaN,Agrícola,ATENDIMENTO A COOPERADOS (MCR 5-2),SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2438,"1,12E+13",01/01/2015,05/07/2021,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2477,"1,12E+13",01/07/2015,27/09/2018,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,FARELO,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,NaN
2497,"1,12E+13",20/07/2017,27/09/2018,Comercialização,Agrícola,Aquisição de Matéria Prima direto do Produtor/...,SOJA,ÓLEO,Ano Civil / Ano de Exploração,NaN,Litro,Litro,Valor inválido,0.0,NaN
2529,"1,13E+13",01/07/2013,NaN,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
2530,"1,13E+13",01/07/2013,22/11/2018,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Tonelada,Tonelada,Não consorciado,0.0,3.0
2531,"1,13E+13",21/06/2022,30/06/2022,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Tonelada,Tonelada,Não consorciado,0.0,3.0
2614,"1,13E+13",01/01/2014,30/06/2017,Comercialização,Agrícola,FGPP-Financiamento para Garantia de Preços ao ...,SOJA,VARIEDADE,Safrinha (2ª Safra),Não zoneado,Quilograma,Quilograma,Não consorciado,0.0,3.0
2829,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2830,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2831,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Irrigadas,Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2832,"1,30E+13",09/04/2020,09/04/2020,Custeio,Agrícola,COVID-19 - Resolução 4801/2020,SOJA,NÃO SE APLICA,Irrigadas,Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2923,"1,30E+13",14/04/2020,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2924,"1,30E+13",09/02/2021,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),NaN,Hectare,Tonelada,Não consorciado,0.0,3.0
2925,"1,30E+13",09/02/2021,15/02/2021,Custeio,Agrícola,ESTIAGEM - Resolução 4802/2020,SOJA,NÃO SE APLICA,Safra de Verão (1ª Safra),Não zoneado,Hectare,Tonelada,Não consorciado,0.0,3.0
2965,"1,13E+13",17/08/2017,13/09/2017,Comercialização,Agrícola,Financiamento para Aquisição da Produção/Mater...,SOJA,NÃO SE APLICA,Ano Civil / Ano de Exploração,NaN,Tonelada,Tonelada,Valor inválido,0.0,3.0

In [13]:
ref_bacen = sicor_basico[sicor_basico['CD_EMPREENDIMENTO'].isin(set(cod_empreendimento['CODIGO']))]
ref_bacen

,REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,...,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN
4,510409466,1,79342069,07/17/2020 00:00:00,04/15/2021 00:00:00,5,3333,300,NaN,PR,...,78.70,NaN,NaN,02/15/2021 00:00:00,10/13/2020 00:00:00,02/12/2021 00:00,10/10/2020 00:00,NaN,NaN,NaN
5,512711289,1,89990501,09/09/2021 00:00,07/20/2022 00:00:00,5,2222,201,1181521.0,RS,...,13.56,1.0,NaN,04/25/2022 00:00:00,11/01/2021 00:00,02/25/2022 00:00:00,09/10/2021 00:00,NaN,NaN,"2,02E+12"
8,513444051,1,79342069,02/02/2022 00:00,11/11/2022 00:00,5,3333,300,NaN,PR,...,64.22,NaN,NaN,08/20/2022 00:00:00,03/10/2022 00:00,08/10/2022 00:00,03/08/2022 00:00,NaN,NaN,"2,02E+12"
21,511110828,1,0,10/30/2020 00:00:00,11/29/2021 00:00:00,3,4444,430,NaN,MT,...,670.00,NaN,NaN,06/30/2021 00:00:00,02/15/2021 00:00:00,06/01/2021 00:00,02/01/2021 00:00,NaN,10.75,NaN
26,512498723,1,92702067,08/10/2021 00:00,05/20/2022 00:00:00,1,2222,201,NaN,RS,...,2.33,1.0,NaN,02/15/2022 00:00:00,09/15/2021 00:00:00,01/15/2022 00:00:00,08/15/2021 00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048559,510510741,2,0,07/29/2020 00:00:00,06/20/2021 00:00:00,10,2222,300,NaN,RS,...,15.00,1.0,NaN,04/20/2021 00:00:00,09/20/2020 00:00:00,04/01/2021 00:00,09/01/2020 00:00,NaN,11.07,NaN
1048560,508609214,1,0,07/12/2019 00:00,07/03/2020 00:00,4,2222,201,NaN,PR,...,0.45,NaN,NaN,12/31/2019 00:00:00,08/31/2019 00:00:00,11/10/2019 00:00,07/15/2019 00:00:00,NaN,8.41,NaN
1048561,512900717,1,60746948,10/07/2021 00:00,11/21/2022 00:00:00,1,3333,201,NaN,MG,...,7.41,NaN,NaN,09/26/2022 00:00:00,05/31/2022 00:00:00,07/29/2022 00:00:00,04/29/2022 00:00:00,NaN,NaN,NaN
1048564,510710890,1,79342069,08/26/2020 00:00:00,08/16/2022 00:00:00,3,2222,300,1181521.0,PR,...,4.84,1.0,NaN,06/10/2022 00:00,08/20/2020 00:00:00,06/01/2022 00:00,08/18/2020 00:00:00,NaN,NaN,NaN
1048568,510495386,2,0,07/28/2020 00:00:00,07/27/2021 00:00:00,10,2222,300,NaN,RS,...,5.86,1.0,NaN,04/30/2021 00:00:00,11/30/2020 00:00:00,03/01/2021 00:00,11/01/2020 00:00,NaN,9.56,NaN

In [17]:
glebas = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/03_TABS_COMP_BASICAS_OPERACOES_CREDITO_RURAL_PROAGRO_RECURSOS_PUB/Glebas.csv', sep=';', encoding='ISO-8859-1')
glebas_soja = glebas[(glebas['REF_BACEN'].isin(set(ref_bacen['REF_BACEN']))) & (glebas['NU_ORDEM'].isin(set(ref_bacen['NU_ORDEM'])))]
glebas_soja

,REF_BACEN,NU_ORDEM,NU_IDENTIFICADOR,NU_INDICE_GLEBA,NU_INDICE_PONTO,VL_LATITUDE,VL_LONGITUDE,CGL_VL_ALTITUDE
0,514166720,1,1,0,17,"-28,105725","-52,845429","533,61"
4,510160257,1,5,4,23,"-28,585877","-52,120624","678,4"
5,513678782,1,1,2,29,"-27,581412","-52,909909","494,58"
10,509573108,1,2844600,0,1,"-21,95682","-54,977416",0
13,515100311,1,2,1,35,"-29,445306","-53,171012","462,93"
...,...,...,...,...,...,...,...,...
1048559,512745606,1,8,7,21,"-27,513912","-52,592043","780,59"
1048560,512967973,1,6,5,52,"-23,193704","-50,500879","472,34"
1048561,514319387,1,3472067,0,28,"-31,584751","-53,41307",0
1048565,512312032,1,3,2,28,"-27,937906","-53,11623","394,27"
1048567,508303470,1,1,0,5,"-27,401514","-53,971427",0

In [18]:
# Suponha que 'count_registers' seja uma série que contém contagens para cada valor único em 'REF_BACEN'.
# Primeiro, crie uma série com as contagens dos valores 'REF_BACEN'.
count_registers = glebas_soja['REF_BACEN'].value_counts()

# Em seguida, crie uma lista de valores 'REF_BACEN' que têm menos de 3 registros.
codigos_a_remover = count_registers[count_registers <= 3].index.tolist()

# Finalmente, filtre o DataFrame 'glebas_soja' para manter apenas os registros em que 'REF_BACEN' não está na lista de códigos a serem removidos.
final = glebas_soja[~glebas_soja['REF_BACEN'].isin(codigos_a_remover)]
final.to_csv("filtradoteste.csv")

In [19]:
sicor_cop = pd.read_csv('C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_COP_BASICO.csv', sep =";", encoding='ISO-8859-1')
sicor_cop

,REF_BACEN,NU_ORDEM,DT_COMUNICACAO,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INICIO_COLHEITA,DT_INICIO_PLANTIO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,508778190,1,03/12/2020 00:00,03/20/2020 00:00:00,11/10/2019 00:00,03/16/2020 00:00:00,11/01/2019 00:00,2,3,3,48
1,508651375,1,03/13/2020 00:00:00,03/30/2020 00:00:00,11/18/2019 00:00:00,03/16/2020 00:00:00,11/15/2019 00:00:00,2,1,3,48
2,3320273,1,08/26/2014 00:00:00,10/01/2014 00:00,05/20/2014 00:00:00,10/01/2014 00:00,05/15/2014 00:00:00,2,1,3,48
3,512735896,1,04/29/2022 00:00:00,05/08/2022 00:00,12/20/2021 00:00:00,05/07/2022 00:00,11/01/2021 00:00,2,3,3,48
4,6590243,1,03/17/2016 00:00:00,03/01/2016 00:00,11/03/2015 00:00,03/01/2016 00:00,10/20/2015 00:00:00,2,3,3,48
...,...,...,...,...,...,...,...,...,...,...,...
581000,9717627,1,09/27/2017 00:00:00,11/10/2017 00:00,05/18/2017 00:00:00,11/10/2017 00:00,05/18/2017 00:00:00,2,1,2,48
581001,509346910,1,01/24/2020 00:00:00,02/08/2020 00:00,11/08/2019 00:00,02/07/2020 00:00,11/07/2019 00:00,2,3,2,48
581002,6170376,1,09/18/2015 00:00:00,02/01/2016 00:00,08/07/2015 00:00,02/01/2016 00:00,08/03/2015 00:00,2,3,2,24
581003,9449462,1,07/21/2017 00:00:00,08/10/2017 00:00,02/26/2017 00:00:00,07/30/2017 00:00:00,02/21/2017 00:00:00,2,1,3,17
581004,508608147,1,10/22/2019 00:00:00,05/10/2020 00:00,07/31/2019 00:00:00,04/20/2020 00:00:00,07/01/2019 00:00,2,99,9,31

In [20]:
sicor_cop_glebas = pd.merge(final, sicor_basico, on=['REF_BACEN', 'NU_ORDEM'], how='left')
sicor_cop_glebas

,REF_BACEN,NU_ORDEM,NU_IDENTIFICADOR,NU_INDICE_GLEBA,NU_INDICE_PONTO,VL_LATITUDE,VL_LONGITUDE,CGL_VL_ALTITUDE,CNPJ_IF,DT_EMISSAO,...,VL_AREA_FINANC,CD_SUBPROGRAMA,VL_PRODUTIV_OBTIDA,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN
0,514166720,1,1,0,17,"-28,105725","-52,845429","533,61",87779625.0,07/14/2022 00:00:00,...,9.34,1.0,NaN,04/20/2023 00:00:00,11/30/2022 00:00:00,03/15/2023 00:00:00,11/05/2022 00:00,NaN,NaN,NaN
1,510160257,1,5,4,23,"-28,585877","-52,120624","678,4",87795639.0,05/26/2020 00:00:00,...,57.80,1.0,3.6,11/10/2020 00:00,07/05/2020 00:00,10/25/2020 00:00:00,06/10/2020 00:00,NaN,NaN,NaN
2,513678782,1,1,2,29,"-27,581412","-52,909909","494,58",2663426.0,04/06/2022 00:00,...,15.00,1.0,NaN,11/17/2022 00:00:00,06/30/2022 00:00:00,10/19/2022 00:00:00,06/01/2022 00:00,NaN,11.93,"2,02E+12"
3,509573108,1,2844600,0,1,"-21,95682","-54,977416",0,0.0,12/19/2019 00:00:00,...,236.00,NaN,NaN,08/30/2020 00:00:00,03/20/2020 00:00:00,07/01/2020 00:00,03/16/2020 00:00:00,NaN,7.50,NaN
4,515100311,1,2,1,35,"-29,445306","-53,171012","462,93",87067757.0,11/25/2022 00:00:00,...,2.30,1.0,NaN,05/10/2023 00:00,12/20/2022 00:00:00,03/10/2023 00:00,11/30/2022 00:00:00,NaN,NaN,"2,02E+12"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236461,512745606,1,8,7,21,"-27,513912","-52,592043","780,59",87780268.0,09/15/2021 00:00:00,...,29.11,1.0,NaN,03/30/2022 00:00:00,12/15/2021 00:00:00,02/01/2022 00:00,11/15/2021 00:00:00,NaN,NaN,NaN
236462,512967973,1,6,5,52,"-23,193704","-50,500879","472,34",79086997.0,10/21/2021 00:00:00,...,369.24,NaN,NaN,03/10/2022 00:00,11/10/2021 00:00,01/20/2022 00:00:00,09/11/2021 00:00,NaN,NaN,"2,02E+12"
236463,514319387,1,3472067,0,28,"-31,584751","-53,41307",0,0.0,07/29/2022 00:00:00,...,80.00,NaN,NaN,05/31/2023 00:00:00,12/20/2022 00:00:00,05/15/2023 00:00:00,11/10/2022 00:00,NaN,9.34,"2,02E+12"
236464,512312032,1,3,2,28,"-27,937906","-53,11623","394,27",88099247.0,07/16/2021 00:00:00,...,3.00,1.0,NaN,02/28/2022 00:00:00,09/06/2021 00:00,02/28/2022 00:00:00,09/05/2021 00:00,NaN,NaN,NaN
236465,508303470,1,1,0,5,"-27,401514","-53,971427",0,4622657.0,04/29/2019 00:00:00,...,62.00,1.0,NaN,10/22/2019 00:00:00,06/14/2019 00:00:00,09/27/2019 00:00:00,05/20/2019 00:00:00,NaN,NaN,NaN