In [4]:
import pandas as pd

In [5]:
produtos = pd.read_csv(r'../../data/Produto.csv', encoding='ISO-8859-1')

soja = produtos[produtos['DESCRICAO'] == 'SOJA']
soja

FileNotFoundError: [Errno 2] No such file or directory: '../../data/Produto.csv'

In [6]:
empreendimento = pd.read_csv(r'../../data/Empreendimento.csv', sep=';', encoding='ISO-8859-1')
cod_empreendimento =  empreendimento[empreendimento['PRODUTO'] == 'SOJA']
cod_empreendimento

FileNotFoundError: [Errno 2] No such file or directory: '../../data/Empreendimento.csv'

In [ ]:
operacao_credito_estadual = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_OPERACAO_BASICA_ESTADO_2018_ATUAL.csv', sep=';', encoding='ISO-8859-1')
operacao_credito_estadual_antes = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_OPERACAO_BASICA_ESTADO_2013_2017.csv', sep=';', encoding='ISO-8859-1')

In [ ]:
operacao_credito_estadual_total =pd.concat([operacao_credito_estadual,operacao_credito_estadual_antes], axis=0)

In [ ]:
ref_bacen = operacao_credito_estadual_total[operacao_credito_estadual_total['CD_EMPREENDIMENTO'].isin(set(cod_empreendimento['CODIGO']))]

In [ ]:
sicor_cop_basico = pd.read_csv("C:/Users/leall/OneDrive/Área de Trabalho/02_TABS_BASICAS_OPERACAO_CREDITO_RURAL_PROAGRO_RECURSOS_PUBLICOS_PRIVADOS/SICOR_COP_BASICO.csv", sep=';', encoding='ISO-8859-1')
sicor_cop_basico = sicor_cop_basico.drop(columns=['DT_FIM_COLHEITA', 'DT_FIM_PLANTIO', 'DT_INICIO_PLANTIO', 'DT_INICIO_COLHEITA'])
sicor_cop_basico

,REF_BACEN,NU_ORDEM,DT_COMUNICACAO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,508778190,1,03/12/2020 00:00,2,3,3,48
1,508651375,1,03/13/2020 00:00:00,2,1,3,48
2,3320273,1,08/26/2014 00:00:00,2,1,3,48
3,512735896,1,04/29/2022 00:00:00,2,3,3,48
4,6590243,1,03/17/2016 00:00:00,2,3,3,48
...,...,...,...,...,...,...,...
581000,9717627,1,09/27/2017 00:00:00,2,1,2,48
581001,509346910,1,01/24/2020 00:00:00,2,3,2,48
581002,6170376,1,09/18/2015 00:00:00,2,3,2,24
581003,9449462,1,07/21/2017 00:00:00,2,1,3,17
581004,508608147,1,10/22/2019 00:00:00,2,99,9,31

In [ ]:
merged = ref_bacen.merge(sicor_cop_basico, on=['REF_BACEN', 'NU_ORDEM'], how='inner')

merged

,REF_BACEN,NU_ORDEM,CNPJ_IF,DT_EMISSAO,DT_VENCIMENTO,CD_INST_CREDITO,CD_CATEG_EMITENTE,CD_FONTE_RECURSO,CNPJ_AGENTE_INVEST,CD_ESTADO,...,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,DT_COMUNICACAO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,513444051,1,79342069,02/02/2022 00:00,11/11/2022 00:00,5,3333,300,NaN,PR,...,08/10/2022 00:00,03/08/2022 00:00,NaN,NaN,"2,02E+12",08/04/2022 00:00,2,99,3,48
1,513663204,1,82527557,03/31/2022 00:00:00,02/19/2023 00:00:00,5,2222,201,1181521.0,PR,...,09/20/2022 00:00:00,05/15/2022 00:00:00,NaN,NaN,NaN,09/26/2022 00:00:00,2,1,3,24
2,508714917,1,87900411,07/29/2019 00:00:00,07/04/2020 00:00,10,2222,201,NaN,RS,...,03/15/2020 00:00:00,11/01/2019 00:00,NaN,NaN,NaN,03/11/2020 00:00,2,2,3,48
3,512408999,1,87067757,07/28/2021 00:00:00,07/03/2022 00:00,10,2222,201,1181521.0,RS,...,03/09/2022 00:00,10/15/2021 00:00:00,NaN,NaN,NaN,03/02/2022 00:00,2,99,9,48
4,512481389,1,92702067,08/06/2021 00:00,04/20/2022 00:00:00,1,2222,201,NaN,RS,...,12/24/2021 00:00:00,08/20/2021 00:00:00,NaN,NaN,NaN,12/13/2021 00:00:00,2,1,3,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58432,5288763,1,0,02/11/2015 00:00,12/07/2015 00:00,10,2222,300,NaN,PR,...,NaN,NaN,NaN,NaN,NaN,07/31/2015 00:00:00,2,1,3,17
58433,3429802,1,88099247,05/22/2014 00:00:00,01/10/2015 00:00,4,2222,201,NaN,RS,...,NaN,NaN,NaN,NaN,NaN,10/15/2014 00:00:00,2,1,3,17
58434,716006,1,7237373,05/13/2013 00:00:00,02/13/2014 00:00:00,4,2222,502,NaN,SE,...,NaN,NaN,NaN,NaN,NaN,11/04/2013 00:00,2,8,2,48
58435,4470997,2,0,09/25/2014 00:00:00,09/22/2015 00:00:00,10,2222,300,NaN,PR,...,NaN,NaN,NaN,NaN,NaN,01/30/2015 00:00:00,3,1,3,79
58436,5663687,1,2663426,05/06/2015 00:00,02/15/2016 00:00:00,5,2222,201,NaN,RS,...,NaN,NaN,NaN,NaN,NaN,10/05/2015 00:00,2,3,3,24

In [ ]:
glebas = pd.read_csv(r'C:/Users/leall/OneDrive/Área de Trabalho/03_TABS_COMP_BASICAS_OPERACOES_CREDITO_RURAL_PROAGRO_RECURSOS_PUB/Glebas.csv', sep=';', encoding='ISO-8859-1')
glebas_soja = glebas[(glebas['REF_BACEN'].isin(set(merged['REF_BACEN']))) & (glebas['NU_ORDEM'].isin(set(merged['NU_ORDEM'])))]
glebas_soja

,REF_BACEN,NU_ORDEM,NU_IDENTIFICADOR,NU_INDICE_GLEBA,NU_INDICE_PONTO,VL_LATITUDE,VL_LONGITUDE,CGL_VL_ALTITUDE
5,513678782,1,1,2,29,"-27,581412","-52,909909","494,58"
33,512621574,1,3,2,23,"-29,717522","-52,557993","39,21"
37,513364988,1,4,3,21,"-25,779189","-53,342375","424,17"
47,511691096,1,4224550,1,4,"-23,719652","-51,06883",0
52,509326471,1,2,1,8,"-28,689093","-54,034045","364,11"
...,...,...,...,...,...,...,...,...
1048519,512666190,1,5035252,0,16,"-28,139361","-54,676418",0
1048524,512346530,1,4662946,1,4,"-25,959465","-53,801734",0
1048547,512600233,1,2,1,11,"-26,931302","-53,566696","383,09"
1048559,512745606,1,8,7,21,"-27,513912","-52,592043","780,59"
1048565,512312032,1,3,2,28,"-27,937906","-53,11623","394,27"

In [ ]:
count_registers = glebas_soja['REF_BACEN'].value_counts()

codigos_a_remover = count_registers[count_registers <= 3].index.tolist()

final = glebas_soja[~glebas_soja['REF_BACEN'].isin(codigos_a_remover)]

In [ ]:
sicor_op_glebas = pd.merge(final, merged, on=['REF_BACEN', 'NU_ORDEM'], how='left')
sicor_op_glebas

,REF_BACEN,NU_ORDEM,NU_IDENTIFICADOR,NU_INDICE_GLEBA,NU_INDICE_PONTO,VL_LATITUDE,VL_LONGITUDE,CGL_VL_ALTITUDE,CNPJ_IF,DT_EMISSAO,...,DT_INIC_COLHEITA,DT_INIC_PLANTIO,VL_JUROS_ENC_FINAN_POSFIX,VL_PERC_CUSTO_EFET_TOTAL,CD_CONTRATO_STN,DT_COMUNICACAO,CD_STATUS,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,513678782,1,1,2,29,"-27,581412","-52,909909","494,58",2663426.0,04/06/2022 00:00,...,10/19/2022 00:00:00,06/01/2022 00:00,NaN,11.93,"2,02E+12",11/01/2022 00:00,2.0,2.0,3.0,17.0
1,512621574,1,3,2,23,"-29,717522","-52,557993","39,21",95424891.0,08/25/2021 00:00:00,...,04/01/2022 00:00,11/03/2021 00:00,NaN,NaN,NaN,03/04/2022 00:00,3.0,99.0,9.0,48.0
2,513364988,1,4,3,21,"-25,779189","-53,342375","424,17",971300.0,01/14/2022 00:00:00,...,06/11/2022 00:00,02/19/2022 00:00:00,NaN,NaN,"2,02E+12",05/11/2022 00:00,2.0,1.0,3.0,110.0
3,511691096,1,4224550,1,4,"-23,719652","-51,06883",0,0.0,03/12/2021 00:00,...,07/05/2021 00:00,03/22/2021 00:00:00,NaN,24.50,NaN,06/04/2021 00:00,2.0,1.0,3.0,48.0
4,509326471,1,2,1,8,"-28,689093","-54,034045","364,11",90729369.0,10/31/2019 00:00:00,...,03/25/2020 00:00:00,11/05/2019 00:00,NaN,NaN,NaN,03/27/2020 00:00:00,2.0,99.0,3.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60329,512666190,1,5035252,0,16,"-28,139361","-54,676418",0,0.0,08/31/2021 00:00:00,...,01/05/2022 00:00,09/02/2021 00:00,NaN,14.42,"2,02E+12",01/07/2022 00:00,2.0,1.0,3.0,48.0
60330,512346530,1,4662946,1,4,"-25,959465","-53,801734",0,0.0,07/21/2021 00:00:00,...,02/01/2022 00:00,09/01/2021 00:00,NaN,11.39,"2,02E+12",01/12/2022 00:00,2.0,1.0,3.0,48.0
60331,512600233,1,2,1,11,"-26,931302","-53,566696","383,09",88099247.0,08/23/2021 00:00:00,...,02/01/2022 00:00,09/10/2021 00:00,NaN,NaN,NaN,01/03/2022 00:00,2.0,99.0,3.0,48.0
60332,512745606,1,8,7,21,"-27,513912","-52,592043","780,59",87780268.0,09/15/2021 00:00:00,...,02/01/2022 00:00,11/15/2021 00:00:00,NaN,NaN,NaN,03/28/2022 00:00:00,2.0,1.0,2.0,48.0
60333,512312032,1,3,2,28,"-27,937906","-53,11623","394,27",88099247.0,07/16/2021 00:00:00,...,02/28/2022 00:00:00,09/05/2021 00:00,NaN,NaN,NaN,12/06/2021 00:00,2.0,2.0,3.0,48.0

In [ ]:
relatorio_glebas = sicor_op_glebas[['REF_BACEN',	'NU_ORDEM',	'DT_EMISSAO',	'DT_VENCIMENTO',	'CD_ESTADO',	'CD_EMPREENDIMENTO',	'CD_PROGRAMA'	,'CD_TIPO_IRRIGACAO'	,'CD_TIPO_AGRICULTURA',	'CD_FASE_CICLO_PRODUCAO',	'CD_TIPO_CULTIVO',	'CD_TIPO_GRAO_SEMENTE',	'DT_FIM_COLHEITA',	'DT_FIM_PLANTIO','DT_INIC_COLHEITA','DT_INIC_PLANTIO','DT_COMUNICACAO','CD_CICLO_CULTIVAR','CD_TIPO_SOLO',	'CD_EVENTO']]
relatorio_glebas

,REF_BACEN,NU_ORDEM,DT_EMISSAO,DT_VENCIMENTO,CD_ESTADO,CD_EMPREENDIMENTO,CD_PROGRAMA,CD_TIPO_IRRIGACAO,CD_TIPO_AGRICULTURA,CD_FASE_CICLO_PRODUCAO,CD_TIPO_CULTIVO,CD_TIPO_GRAO_SEMENTE,DT_FIM_COLHEITA,DT_FIM_PLANTIO,DT_INIC_COLHEITA,DT_INIC_PLANTIO,DT_COMUNICACAO,CD_CICLO_CULTIVAR,CD_TIPO_SOLO,CD_EVENTO
0,513678782,1,04/06/2022 00:00,02/15/2023 00:00:00,RS,"1,20E+13",1.0,1.0,3.0,22.0,0.0,8.0,11/17/2022 00:00:00,06/30/2022 00:00:00,10/19/2022 00:00:00,06/01/2022 00:00,11/01/2022 00:00,2.0,3.0,17.0
1,512621574,1,08/25/2021 00:00:00,10/28/2022 00:00:00,RS,"1,20E+13",50.0,1.0,7.0,22.0,3.0,8.0,04/30/2022 00:00:00,12/31/2021 00:00:00,04/01/2022 00:00,11/03/2021 00:00,03/04/2022 00:00,99.0,9.0,48.0
2,513364988,1,01/14/2022 00:00:00,08/15/2022 00:00:00,PR,"1,20E+13",1.0,1.0,7.0,22.0,3.0,3.0,06/11/2022 00:00,02/19/2022 00:00:00,06/11/2022 00:00,02/19/2022 00:00:00,05/11/2022 00:00,1.0,3.0,110.0
3,511691096,1,03/12/2021 00:00,11/15/2021 00:00:00,PR,"1,20E+13",1.0,1.0,7.0,22.0,0.0,8.0,07/19/2021 00:00:00,03/30/2021 00:00:00,07/05/2021 00:00,03/22/2021 00:00:00,06/04/2021 00:00,1.0,3.0,48.0
4,509326471,1,10/31/2019 00:00:00,07/05/2024 00:00,RS,"1,20E+13",50.0,1.0,7.0,22.0,2.0,8.0,05/05/2020 00:00,12/05/2019 00:00,03/25/2020 00:00:00,11/05/2019 00:00,03/27/2020 00:00:00,99.0,3.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60329,512666190,1,08/31/2021 00:00:00,08/23/2022 00:00:00,RS,"1,20E+13",1.0,1.0,3.0,22.0,0.0,8.0,02/05/2022 00:00,09/25/2021 00:00:00,01/05/2022 00:00,09/02/2021 00:00,01/07/2022 00:00,1.0,3.0,48.0
60330,512346530,1,07/21/2021 00:00:00,07/06/2022 00:00,PR,"1,20E+13",1.0,1.0,7.0,22.0,0.0,8.0,02/10/2022 00:00,09/15/2021 00:00:00,02/01/2022 00:00,09/01/2021 00:00,01/12/2022 00:00,1.0,3.0,48.0
60331,512600233,1,08/23/2021 00:00:00,06/29/2022 00:00:00,SC,"1,20E+13",1.0,1.0,7.0,22.0,0.0,0.0,03/30/2022 00:00:00,11/10/2021 00:00,02/01/2022 00:00,09/10/2021 00:00,01/03/2022 00:00,99.0,3.0,48.0
60332,512745606,1,09/15/2021 00:00:00,06/29/2022 00:00:00,RS,"1,20E+13",1.0,1.0,7.0,22.0,0.0,8.0,03/30/2022 00:00:00,12/15/2021 00:00:00,02/01/2022 00:00,11/15/2021 00:00:00,03/28/2022 00:00:00,1.0,2.0,48.0
60333,512312032,1,07/16/2021 00:00:00,05/30/2022 00:00:00,RS,"1,20E+13",1.0,1.0,5.0,22.0,0.0,8.0,02/28/2022 00:00:00,09/06/2021 00:00,02/28/2022 00:00:00,09/05/2021 00:00,12/06/2021 00:00,2.0,3.0,48.0